import type { CarDefinition } from '../types/game.js';

export const CAR_DEFINITIONS: CarDefinition[] = [
  {
    id: 'racer-red',
    name: 'Racer Red',
    color: 0xe53935,
    accentColor: 0xffcdd2,
    maxSpeed: 118,
    acceleration: 85,
    handling: 0.8,
    braking: 58,
  },
  {
    id: 'sir-skids',
    name: 'Sir Skids-a-Lot',
    color: 0x1e88e5,
    accentColor: 0xbbdefb,
    maxSpeed: 132,
    acceleration: 90,
    handling: 0.6,
    braking: 50,
  },
  {
    id: 'captain-crumb',
    name: 'Captain Crumb',
    color: 0xfdd835,
    accentColor: 0xfff9c4,
    maxSpeed: 112,
    acceleration: 82,
    handling: 0.75,
    braking: 60,
  },
  {
    id: 'butterknife',
    name: 'The Butterknife',
    color: 0x43a047,
    accentColor: 0xc8e6c9,
    maxSpeed: 102,
    acceleration: 76,
    handling: 0.95,
    braking: 65,
  },
  {
    id: 'sauce-boss',
    name: 'Sauce Boss',
    color: 0xff6f00,
    accentColor: 0xffe0b2,
    maxSpeed: 128,
    acceleration: 95,
    handling: 0.65,
    braking: 54,
  },
  {
    id: 'lil-pepper',
    name: "Lil' Pepper",
    color: 0xab47bc,
    accentColor: 0xe1bee7,
    maxSpeed: 115,
    acceleration: 83,
    handling: 0.78,
    braking: 62,
  },
];
