import type { CarDefinition } from '../types/game.js';

export const CAR_DEFINITIONS: CarDefinition[] = [
  {
    id: 'racer-red',
    name: 'Racer Red',
    color: 0xe53935,
    accentColor: 0xffcdd2,
    maxSpeed: 84,
    acceleration: 123,
    handling: 0.8,
    braking: 90,
  },
  {
    id: 'sir-skids',
    name: 'Sir Skids-a-Lot',
    color: 0x1e88e5,
    accentColor: 0xbbdefb,
    maxSpeed: 94,
    acceleration: 129,
    handling: 0.6,
    braking: 80,
  },
  {
    id: 'captain-crumb',
    name: 'Captain Crumb',
    color: 0xfdd835,
    accentColor: 0xfff9c4,
    maxSpeed: 80,
    acceleration: 117,
    handling: 0.75,
    braking: 95,
  },
  {
    id: 'butterknife',
    name: 'The Butterknife',
    color: 0x43a047,
    accentColor: 0xc8e6c9,
    maxSpeed: 73,
    acceleration: 108,
    handling: 0.95,
    braking: 105,
  },
  {
    id: 'sauce-boss',
    name: 'Sauce Boss',
    color: 0xff6f00,
    accentColor: 0xffe0b2,
    maxSpeed: 91,
    acceleration: 135,
    handling: 0.65,
    braking: 85,
  },
  {
    id: 'lil-pepper',
    name: "Lil' Pepper",
    color: 0xab47bc,
    accentColor: 0xe1bee7,
    maxSpeed: 82,
    acceleration: 119,
    handling: 0.78,
    braking: 98,
  },
];
